### ISSUE TITLE
Add the ability to execute 'zarf tools registry login'

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/setup-zarf#36]
Relates to https://github.com/defenseunicorns/setup-zarf/issues/35

Users would like the ability for this action to do the following:
- Log in to [registry1.dso.mil](http://registry1.dso.mil/) (zarf tools registry login)

Acceptance criteria:
- test(s) in place that verify the behavior of the logic
- CI has validated the changes and is passing ✅

**Comment by jeff-mccoy** [comment]
This still feels like it might be better using https://github.com/docker/login-action, but less opposed to adding this vs package create/deploy.

**Comment by lucasrod16** [comment]
This feature is no longer needed. See this [comment](https://github.com/defenseunicorns/setup-zarf/issues/35#issuecomment-1312345349) for more information
